### PR TITLE
Project update

### PR DESCRIPTION
**Pull request by carmineos**
Maybe better move the Readme and the Todo in the main folder.
Also main project still has some leftover files from Dexy which i didn't touch

I've updated the project files to use the PackageReference style, updated the nugets, moved the main project into a subfolder, moved the Shaders project to another subfolder with edited the ObjectFileOutput property so the .cso should now be output directly into the CodeWalker\Shaders\ folder (hopefully lol).

### CODE REVIEW

**Comment by dexyfex** [comment]
There's just too many files modified here, and merge conflicts etc... need to find a different approach i guess.

**Comment by carmineos** [comment]
For now I could rebase and do it again except for https://github.com/dexyfex/CodeWalker/pull/49/commits/4475d4c80b8600fba46b3e6d003cc6358907e466

**Comment by dexyfex** [comment]
PackageReference change makes sense, I assume that's just a new approach? Does it require any particular VS version? (I'm running a bit behind at the moment)

And updating the packages is fine, although will be interesting to see if SharpDX update causes any issues (there were some things i had to change in the past when upgrading it).

Shaders project change is also good, makes sense to separate that and simplifies some things.

**Comment by dexyfex** [comment]
Probably best to try and keep different areas of functionality in separate PRs also, just to make it a bit more manageable for me :)

**Comment by carmineos** [comment]
PackageReference works with VS2017+ and since 15.7 you can right click on the packages.config and select Migrate to PackageReference to automate that.

SharpDX seems fine, I've been using a build from this branch for months.

**Pull request closed without merging**
