### PR TITLE
fix missing add / remove path node link buttons

### PR DESCRIPTION
**Pull request by ook3D**

### CODE REVIEW

**Comment by dexyfex** [comment]
can you please explain what you actually did here?

**Comment by ook3D** [comment]
> can you please explain what you actually did here?

i moved the button to a new position in the designer, seems to have fixed it vanishing upon compilation

**Comment by dexyfex** [comment]
Manually performed this update and adjusted positions of controls to fit slightly better

**Comment by ChickenDipper1** [comment]
Please dear god merge this request, this is still an issue and its a nightmare!

**Pull request closed without merging**
