### PR TITLE
ymap: add calculate all flags/extents

### PR DESCRIPTION
**Pull request by PichotM**

### CODE REVIEW

**Comment by carmineos** [comment]
This should work based on the selected nodes in the treeview. If more than 1 ymap is selected, display panel with options that apply to all of them.

**Comment by dexyfex** [comment]
Can you please just make the new controls adhere to the naming convention thanks :)

**Comment by PichotM** [comment]
I will do that as soon as possible - just busy right now :)
Thanks for the review

**Comment by PichotM** [comment]
This PR is fixed

**Comment by dexyfex** [comment]
Not needed anymore due to auto-calculate flags/extents options in project window, it will achieve the same result when saving the ymaps.

**Pull request closed without merging**
