### PR TITLE
Updated Light Editor & Fix Capsule Rotate, Shaders

### PR DESCRIPTION
**Pull request by kirill-mapper**
- Update widget transform 
- Add rotation snapping angle
- Fixed capsule rotation 
- Updating capsule shaders using extent, culling plane 
- Updating the functionality of the Light Editor, adding the missing LigthHash parameter, selecting the Flashiness type and light flags, added "Reset" direction and "Calculate" tangent buttons, changed UI

### CODE REVIEW

**Comment by dexyfex** [comment]
I noticed with the culling plane change in LightPS.hlsli, there's incorrect culling happening for most vanilla capsule lights... but also the original culling code for capsule lights doesn't seem correct at all. Are capsule lights supposed to use the culling plane?

**Comment by kirill-mapper** [comment]
> I noticed with the culling plane change in LightPS.hlsli, there's incorrect culling happening for most vanilla capsule lights... but also the original culling code for capsule lights doesn't seem correct at all. Are capsule lights supposed to use the culling plane?

Yes. The culling problem also occurs with all other light sources, since there is no dependency with the "Use Cull Plane" flag. It is necessary to provide for the Cull plane to be displayed only when the flag is turned on, so that there is a complete match with the game

**Comment by dexyfex** [comment]
Ok, then I guess I should really make it use that flag, I didn't realise there's such a thing. I guess it's just turned off for most capsules?

**Comment by kirill-mapper** [comment]
> Ok, then I guess I should really make it use that flag, I didn't realise there's such a thing. I guess it's just turned off for most capsules?
Well, optional. For example, on buildings with long neon lights, most capsules have a flag turned on to avoid highlighting other walls

**Comment by dexyfex** [comment]
Thanks. Do you know which flag this actually is? I guess those flags aren't documented in CodeWalker yet.

**Comment by kirill-mapper** [comment]
Flags:
262144 - Use Cull Plane
I added all the light flags to the PR, but without the numeric values ​​in the name in the check box. This made the window more compact

**Comment by dexyfex** [comment]
Ah thanks, somehow I missed that.

**Comment by dexyfex** [comment]
Manually merged and added light culling toggle by the flag in rendering code

**Pull request closed without merging**
