### PR TITLE
Updated YND node flag names and node colours

### PR DESCRIPTION
**Pull request by ook3D**
Big thanks to DurtyFree and his really old pending PR 😄

### CODE REVIEW

**Comment by lfshr** [comment]
Ah, nice to see my old work get put to good use!

**Comment by ook3D** [comment]
> Ah, nice to see my old work get put to good use!

if you want to work on some more research for them, im more than interested 😃

**Comment by lfshr** [comment]
@dexyfex I think probably hold off on this. My enthusiasm has been reinvigorated lately. I have a branch laying around somewhere that recalculated the indices that I want to have a crack at again.

**Comment by FilipeCuco** [comment]
@ook3D when you try to import a model with embed textures to RPF an error occurs

**Comment by ook3D** [comment]
yes i committed something that breaks it, use older commit

**Pull request closed without merging**
