### PR TITLE
Update MetaNames.cs: Huge name update

### PR DESCRIPTION
**Pull request by Yhwhdios**
I (Carl Johnson) added a huge amount of hashes from my dictionary, If you want me to upload my dictionary I'll do it asap

### CODE REVIEW

**Comment by Yhwhdios** [comment]
Updates thanks to Siprus

**Comment by carmineos** [comment]
Looks like you added a MetaNames.cs duplicated file in the root folder of the repo

**Comment by Yhwhdios** [comment]
> Looks like you added a MetaNames.cs duplicated file in the root folder of the repo

Deleted it, sorry about that

**Comment by dexyfex** [comment]
Manually merged to resolve conflicts

**Pull request closed without merging**
